version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
